/*EMP 테이블에 데이터를 추가, 수정, 삭제하는 SQL문을 작성하고 
그 중간에 저장점을 설정하고 그 결과를 출력하라.*/
INSERT INTO EMP
(EMPNO, ENAME, JOB,
MGR, HIREDATE, SAL, COMM,DEPTNO)
VALUES ('1111', 'HONG', 'INTERN',
NULL,'20210506', 500, NULL, 10);

UPDATE EMP
SET SAL = SAL + 60
WHERE DEPTNO = 10;

SAVEPOINT SVPT1;

DELETE
FROM EMP
WHERE ENAME ='HONG';

SELECT *
FROM EMP;
/*[과제10-1]에서 작성한 SQL문들에 설정된 저장점까지 ROLLBACK을 수행하는 문장을 추가하고 
그 결과를 출력하라. */
INSERT INTO EMP
(EMPNO, ENAME, JOB,
MGR, HIREDATE, SAL, COMM,DEPTNO)
VALUES ('1111', 'HONG', 'INTERN',
NULL,'20210506', 500, NULL, 10);

UPDATE EMP
SET SAL = SAL + 60
WHERE DEPTNO = 10;

SAVEPOINT SVPT1;

DELETE
FROM EMP
WHERE ENAME ='HONG';

ROLLBACK TO SVPT1;

SELECT *
FROM EMP;

/*[과제10-2]에서 작성한 SQL문들에 저장점을 
지정하지 않는 ROLLBACK문장을 추가하고 그 결과를 출력하라.*/
INSERT INTO EMP
(EMPNO, ENAME, JOB,
MGR, HIREDATE, SAL, COMM,DEPTNO)
VALUES ('1111', 'HONG', 'INTERN',
NULL,'20210506', 500, NULL, 10);

UPDATE EMP
SET SAL = SAL + 60
WHERE DEPTNO = 10;

SAVEPOINT SVPT1;

DELETE
FROM EMP
WHERE ENAME ='HONG';

ROLLBACK TO SVPT1;

ROLLBACK;

SELECT *
FROM EMP;

/*시스템 관리자로 접속하여 임의의 유저를 생성 후 생성한 유저로 접속하여 
임의의 테이블을 생성하거나 기존 테이블에서 데이터를 조회하는 SQL문을 작성하고 
실행해보고 그 결과를 출력하라.*/
CONN SYSTEM/9805
CREATE USER C##TEST IDENTIFIED BY TEST1;
CONN C##TEST/TEST1
CREATE TABLE GRADE ( SUBJECT VARCHAR2(10), SCORE NUMBER);
SELECT * FROM GRADE;*/

/*[과제10-4]에서 생성한 유저에게 다른 유저, 세션, 테이블 생성 권한을 부여하라. 
그런 다음 그 유저로 접속하여 임의의 테이블을 생성한 뒤 데이터를 추가하고
그 데이터를 조회하는 SQL문을 작성하고 그 실행 결과를 출력하라.*/
CONN SYSTEM/9805
CREATE ROLE C##LOGIN_TABLE;
GRANT CREATE USER, CREATE SESSION, CREATE TABLE TO C##LOGIN_TABLE;
GRANT C##LOGIN_TABLE TO C##TEST;
GRANT CONNECT, RESOURCE, DBA TO C##TEST;
CONN C##TEST/TEST1
CREATE TABLE GRADE ( SUBJECT VARCHAR2(10) NOT NULL, SCORE NUMBER);
INSERT INTO GRADE(SUBJECT, SCORE) VALUES ('DATABASE',100);
SELECT * FROM GRADE;


/*USER삭제*/
CONN SYSTEM/9805
DROP USER C##TEST CASCADE;