
SELECT TEAM_ID TEAM_ID, COUNT(*) ÀÎ¿ø¼ö, ROUND(AVG(HEIGHT),1) Æò±ÕÅ°, ROUND(AVG(WEIGHT),1) Æò±Õ¸ö¹«°Ô
FROM PLAYER
WHERE E_PLAYER_NAME IS NOT NULL
GROUP BY TEAM_ID
HAVING COUNT(*) >= 20
ORDER BY COUNT(*) DESC
FETCH NEXT 4 ROWS ONLY;

SELECT ENAME ÀÌ¸§,JOB ¿ªÇÒ,  HIREDATE ÀÔ»çÀÏ, SAL ¿ù±Þ¿©
FROM EMP
WHERE JOB = 'CLERK' OR JOB = 'MANAGER'
ORDER BY JOB, HIREDATE DESC, SAL;
/*
SELECT JOB ¿ªÇÒ, COUNT(*) ÀÎ¿ø¼ö, SUM(SAL*12+NVL(COMM,0)) ¿¬ºÀÃÑÇÕ, ROUND(AVG(SAL*12+NVL(COMM,0)),0) ¿¬ºÀÆò±Õ, ROUND(STDDEV(SAL*12+NVL(COMM,0)),0) ¿¬ºÀÇ¥ÁØÆíÂ÷
FROM EMP
GROUP BY JOB
HAVING AVG(SAL*12+NVL(COMM,0)) > 30000;*/