
select EMPNO 사원번호, ENAME 이름, JOB 직무, DEPTNO 부서번호
FROM EMP
WHERE DEPTNO = 10
UNION
select EMPNO 사원번호, ENAME 이름, JOB 직무, DEPTNO 부서번호
FROM EMP
WHERE DEPTNO = 20
ORDER BY 4;

select EMPNO 사원번호, ENAME 이름, JOB 직무, DEPTNO 부서번호
FROM EMP
WHERE DEPTNO = 20
MINUS
select EMPNO 사원번호, ENAME 이름, JOB 직무, DEPTNO 부서번호
FROM EMP
WHERE JOB = 'ANALYST';

SELECT LEVEL, LPAD(' ', 4 * (LEVEL- 1)) | | EMPNO 사원, MGR 관리자, JOB 직무,
CONNECT_BY_ISLEAF ISLEAF
FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR;

SELECT LEVEL, LPAD(' ', 4 * (LEVEL- 1)) | | EMPNO 사원, MGR 관리자,
CONNECT_BY_ISLEAF ISLEAF
FROM EMP
START WITH EMPNO = 7876 OR EMPNO = 7369
CONNECT BY PRIOR MGR = EMPNO;

SELECT E1.EMPNO 사원번호,E1.JOB 사원직무, E1.MGR 상위관리자, E2.JOB 상위관리자직무,  E2.MGR 차상위관리자
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
ORDER BY E1.EMPNO;

SELECT E1.EMPNO 사원번호,E1.JOB 사원직무, E1.MGR 상위관리자, E2.JOB 상위관리자직무,  E2.MGR 차상위관리자
FROM EMP E1 LEFT OUTER JOIN EMP E2
ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;